/** Local, resumable contact-sheet reviewer. Run: npm run images:review */
import { createServer } from 'node:http';
import { createReadStream, existsSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { spawn } from 'node:child_process';
import { extname } from 'node:path';
import { confinedPath } from './lib/confined-path.ts';
import { approvalKey, sourceIdentity } from './lib/source-identity.ts';
import { completeVehicle, decisionFor, emptyReviewProgress, orderedKeptImages, reviewStats, setDecision } from './lib/review-state.ts';

const PORT = Number(process.env.PORT ?? 4180);
const MANIFEST = 'src/data/generated/images.json';
const PROGRESS = 'scripts/image-review-progress.json';
const APPROVALS = 'scripts/image-approvals.json';
const REJECTS = 'scripts/image-rejects.txt';
const CATALOG = 'src/data/generated/catalog.slim.json';
const DIR = 'public/vehicles';

const readJson = (path, fallback) => existsSync(path) ? JSON.parse(readFileSync(path, 'utf8')) : fallback;
const writeJson = (path, value) => writeFileSync(path, JSON.stringify(value, null, 2) + '\n');
const readProgress = () => readJson(PROGRESS, emptyReviewProgress());
const saveProgress = (progress) => writeJson(PROGRESS, progress);

function vehicleNames() {
  const names = new Map();
  const slim = readJson(CATALOG, null);
  if (!slim?.d || !Array.isArray(slim.r)) return names;
  for (const row of slim.r) {
    const [id, makeIdx, modelIdx, genIdx, y0, y1] = row;
    names.set(id, { name: `${slim.d.make[makeIdx]} ${slim.d.model[modelIdx]}`, detail: `${slim.d.generation[genIdx]}, ${y0}-${y1}` });
  }
  return names;
}

function buildReview() {
  const manifest = readJson(MANIFEST, {});
  const progress = readProgress();
  const names = vehicleNames();
  const vehicles = Object.entries(manifest).map(([vehicleId, images]) => ({
    vehicleId,
    ...(names.get(vehicleId) ?? { name: vehicleId, detail: '' }),
    completed: progress.vehicles[vehicleId]?.completed ?? false,
    images: images.map((image, index) => ({ ...image, identity: sourceIdentity(image.sourceUrl), decision: decisionFor(progress, vehicleId, image, index) })),
  }));
  return { vehicles, stats: reviewStats(manifest, progress) };
}

function applyReviewChoices() {
  const manifest = readJson(MANIFEST, {});
  const progress = readProgress();
  const approved = new Set(readJson(APPROVALS, []));
  const rejectedFiles = [];
  const affected = new Set();
  for (const [vehicleId, images] of Object.entries(manifest)) {
    if (!progress.vehicles[vehicleId]?.completed) continue;
    let hasReject = false;
    images.forEach((image, index) => {
      const decision = decisionFor(progress, vehicleId, image, index);
      if (decision === 'reject') { rejectedFiles.push(image.file); hasReject = true; }
      else approved.add(approvalKey(vehicleId, image.sourceUrl));
    });
    const ordered = orderedKeptImages(manifest, progress, vehicleId);
    if (ordered.length < 4 || ordered.length !== images.length) affected.add(vehicleId);
    // Keep rejected entries in place until reject-images.ts has resolved their
    // stable source identities and made the exclusions permanent.
    if (!hasReject) manifest[vehicleId] = ordered;
  }
  writeJson(MANIFEST, manifest);
  writeJson(APPROVALS, [...approved].sort());
  const header = existsSync(REJECTS)
    ? readFileSync(REJECTS, 'utf8').split(/\r?\n/).filter((line) => line.trim().startsWith('#') || line.trim() === '')
    : ['# Generated by the contact-sheet reviewer.'];
  writeFileSync(REJECTS, [...header, ...rejectedFiles].join('\n').replace(/\n+$/, '') + '\n');
  return { affected: [...affected].sort(), rejected: rejectedFiles.length };
}

const send = (res, status, body, type = 'application/json') => {
  res.writeHead(status, { 'content-type': type, 'cache-control': 'no-store' });
  res.end(typeof body === 'string' ? body : JSON.stringify(body));
};
const readBody = (req) => new Promise((resolve) => {
  let raw = '';
  req.on('data', (chunk) => { raw += chunk; if (raw.length > 1e6) req.destroy(); });
  req.on('end', () => { try { resolve(JSON.parse(raw || '{}')); } catch { resolve({}); } });
});

const server = createServer(async (req, res) => {
  const url = new URL(req.url, `http://127.0.0.1:${PORT}`);
  if (url.pathname === '/') return send(res, 200, PAGE, 'text/html; charset=utf-8');
  if (url.pathname === '/favicon.ico') { res.writeHead(204); return res.end(); }
  if (url.pathname === '/api/review') return send(res, 200, buildReview());
  if (url.pathname === '/api/decision' && req.method === 'POST') {
    const { vehicleId, sourceUrl, decision } = await readBody(req);
    if (!vehicleId || !sourceUrl || !['keep', 'reject', 'hero', 'interior'].includes(decision)) return send(res, 400, { error: 'invalid decision' });
    saveProgress(setDecision(readProgress(), vehicleId, sourceUrl, decision));
    return send(res, 200, { ok: true });
  }
  if (url.pathname === '/api/complete' && req.method === 'POST') {
    const { vehicleId } = await readBody(req);
    if (!vehicleId) return send(res, 400, { error: 'vehicleId required' });
    saveProgress(completeVehicle(readProgress(), vehicleId));
    return send(res, 200, { ok: true });
  }
  if ((url.pathname === '/api/next-round' || url.pathname === '/api/apply') && req.method === 'POST') {
    const { affected, rejected } = applyReviewChoices();
    res.writeHead(200, { 'content-type': 'text/plain; charset=utf-8', 'cache-control': 'no-store' });
    if (affected.length === 0) return res.end('Choices saved. All four image slots are filled and no replacements are needed.\n');
    res.write(`Saved choices. Fetching ${affected.length} vehicle(s); ${rejected} rejected image(s).\n`);
    const child = spawn(process.execPath, ['node_modules/vite-node/dist/cli.mjs', 'scripts/reject-images.ts', '--review-progress', '--only', affected.join(',')]);
    child.stdout.on('data', (data) => res.write(data));
    child.stderr.on('data', (data) => res.write(data));
    child.on('close', (code) => {
      if (code === 0) {
        const header = existsSync(REJECTS)
          ? readFileSync(REJECTS, 'utf8').split(/\r?\n/).filter((line) => line.trim().startsWith('#') || line.trim() === '')
          : [];
        writeFileSync(REJECTS, header.join('\n').replace(/\n+$/, '') + '\n');
        let progress = readProgress();
        for (const vehicleId of affected) {
          const current = progress.vehicles[vehicleId] ?? { decisions: {} };
          progress = { ...progress, vehicles: { ...progress.vehicles, [vehicleId]: { ...current, completed: false } } };
        }
        saveProgress(progress);
      }
      res.end(`\n--- next round finished with code ${code} ---\n`);
    });
    child.on('error', (error) => res.end(`\nCould not start the image fetcher: ${error.message}\n`));
    return;
  }
  if (url.pathname.startsWith('/vehicles/')) {
    const name = decodeURIComponent(url.pathname.slice('/vehicles/'.length));
    const path = confinedPath(DIR, name);
    if (!path || !existsSync(path) || !statSync(path).isFile()) return send(res, 404, { error: 'not found' });
    const type = { '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.png': 'image/png' }[extname(path).toLowerCase()];
    if (!type) return send(res, 415, { error: 'not an image' });
    res.writeHead(200, { 'content-type': type, 'cache-control': 'no-store' });
    return createReadStream(path).pipe(res);
  }
  send(res, 404, { error: 'not found' });
});

const PAGE = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Vehicle photo review</title><style>
:root{color-scheme:dark;--bg:#0b0b0d;--card:#17171b;--line:#33333a;--text:#fafafa;--dim:#9999a2;--red:#d84d4d;--gold:#c99a2e;--grey:#74747d;--green:#3d9c6b}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px/1.4 system-ui,sans-serif;padding:20px}main,header{width:min(1500px,100%);margin:auto}header{display:flex;align-items:baseline;gap:14px;margin-bottom:18px}h1,h2,p{margin:0}.count{margin-left:auto;color:var(--dim)}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin-top:18px}.shot{background:var(--card);border:1px solid var(--line);border-radius:12px;overflow:hidden}.frame{aspect-ratio:4/3;background:#000;display:grid;place-items:center}.frame img{width:100%;height:100%;object-fit:contain}.buttons{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;padding:10px}.buttons button,.next{border:1px solid var(--line);border-radius:8px;min-height:42px;color:#fff;background:#24242a;font-weight:700;cursor:pointer}.buttons .reject.active,.buttons .reject:hover{background:var(--red);border-color:var(--red)}.buttons .hero.active,.buttons .hero:hover{background:var(--gold);border-color:var(--gold);color:#17120a}.buttons .interior.active,.buttons .interior:hover{background:var(--grey);border-color:var(--grey)}.meta{padding:0 10px 11px;color:var(--dim);font-size:12px;overflow-wrap:anywhere}.meta a{color:#bbb}.actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.next{background:var(--green);border-color:var(--green);padding:0 24px}.done{text-align:center;background:var(--card);border:1px solid var(--line);border-radius:14px;padding:40px}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;max-width:620px;margin:24px auto}.stats div{border:1px solid var(--line);border-radius:10px;padding:18px}.stats strong{display:block;font-size:34px}.stats span{color:var(--dim)}pre{white-space:pre-wrap;text-align:left;background:#000;border-radius:10px;padding:14px;max-height:45vh;overflow:auto}@media(max-width:1000px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.grid{grid-template-columns:1fr}.stats{grid-template-columns:1fr}}
</style></head><body><header><h1>Vehicle photo review</h1><span class="count" id="count"></span></header><main id="app"></main><script>
const app=document.getElementById('app'),count=document.getElementById('count');let data,current;const esc=(s)=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));async function load(){data=await fetch('/api/review').then(r=>r.json());current=data.vehicles.find(v=>!v.completed);render()}function render(){const s=data.stats;count.textContent=s.completedVehicles+' of '+s.totalVehicles+' vehicles saved';if(!current){app.innerHTML='<div class="done"><h2>Round complete</h2><div class="stats"><div><strong>'+s.approved+'</strong><span>Kept</span></div><div><strong>'+s.rejected+'</strong><span>Rejected</span></div><div><strong>'+s.totalVehicles+'</strong><span>Vehicles</span></div></div><p>Start the next round to replace rejects and fill missing interior slots.</p><div class="actions"><button class="next" id="round">Apply choices and start next round</button></div><pre id="log" hidden></pre></div>';document.getElementById('round').onclick=nextRound;return}app.innerHTML='<h2>'+esc(current.name)+'</h2><p class="count" style="margin:3px 0 0">'+esc(current.detail)+'</p><div class="grid">'+current.images.map(card).join('')+'</div><div class="actions"><button class="next" id="save">Save car and continue</button></div>';document.getElementById('save').onclick=complete;document.querySelectorAll('[data-decision]').forEach(b=>b.onclick=()=>decide(b.dataset.identity,b.dataset.decision))}function card(image){return '<article class="shot"><div class="frame"><img src="/vehicles/'+encodeURIComponent(image.file)+'" alt=""></div><div class="buttons">'+button(image,'reject','Reject')+button(image,'hero','Hero')+button(image,'interior','Interior')+'</div><div class="meta">'+esc(image.file)+(image.sourceUrl?' · <a href="'+esc(image.sourceUrl)+'" target="_blank" rel="noreferrer">source</a>':'')+'</div></article>'}function button(image,decision,label){return '<button class="'+decision+(image.decision===decision?' active':'')+'" data-identity="'+esc(image.identity)+'" data-decision="'+decision+'">'+label+'</button>'}async function decide(identity,decision){const image=current.images.find(i=>i.identity===identity);if(!image)return;const next=image.decision===decision?(decision==='reject'?'keep':decision):decision;await fetch('/api/decision',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({vehicleId:current.vehicleId,sourceUrl:image.sourceUrl,decision:next})});if(next==='hero'||next==='interior')current.images.forEach(i=>{if(i.decision===next)i.decision='keep'});image.decision=next;render()}async function complete(){await fetch('/api/complete',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({vehicleId:current.vehicleId})});await load()}async function nextRound(){const b=document.getElementById('round'),log=document.getElementById('log');b.disabled=true;log.hidden=false;log.textContent='Saving and fetching...\\n';const res=await fetch('/api/next-round',{method:'POST'});const reader=res.body.getReader(),dec=new TextDecoder();for(;;){const x=await reader.read();if(x.done)break;log.textContent+=dec.decode(x.value,{stream:true});log.scrollTop=log.scrollHeight}await load()}load();
</script></body></html>`;

server.listen(PORT, '127.0.0.1', () => {
  const review = buildReview();
  console.log(`Vehicle photo review on http://127.0.0.1:${PORT}`);
  console.log(`${review.stats.completedVehicles} of ${review.stats.totalVehicles} vehicles already saved.`);
});
